### ISSUE TITLE
Error in downloading satellite imagery

### ISSUE THREAD

**Issue by modanesh** [AdaCompNUS/summit#13]
I was following the documentation of Summit ([https://adacompnus.github.io/summit-docs/tutorials/preparing_maps/#obtaining-sumo-networks](https://adacompnus.github.io/summit-docs/tutorials/preparing_maps/#obtaining-sumo-networks)) to get satellite imagery. But when I ran the command `<summit_root>/Scripts/download_imagery.py --dataset <map_name>` to download imagery, I got the following error:
```
Traceback (most recent call last):
  File "download_imagery.py", line 103, in <module>
    sumo_network = carla.SumoNetwork.load(str(DATA_PATH/'{}.net.xml'.format(args.dataset)))
AttributeError: module 'carla' has no attribute 'SumoNetwork'
```

I have the latest version of Summit (0.9.8e).

Thanks.

**Comment by LeeYiyuan** [comment]
SUMMIT builds on top of CARLA and has its own version of the `carla` module. It is likely that you have another version of the `carla` Python modules, probably form CARLA, which cause SUMMIT to resolve to that other version instead of its own.

To check, run `import carla; print(carla.__file__)` and verify which module is being imported.

**Comment by modanesh** [comment]
That most probably was the issue since when I uninstalled carla using pip, it worked fine. So for now, I'm going to close the issue.
Thanks.
