### ISSUE TITLE
Can I know the relationship between this project and carla0.9.8/Co-simulation

### ISSUE THREAD

**Issue by sheepwxy** [AdaCompNUS/summit#5]
you have done a so amazing project.  I'm curious about a question. 
Is the projct the same as carla0.9.8/co-simulaton？
I need to redefine my study route  depending on your answer.

**Comment by LeeYiyuan** [comment]
Hi there,

Thanks for your interest in our work!

In co-simulation, a complex simulator (CARLA, with high-fidelity physics and assets) and a simpler simulator (e.g. SUMO, almost barebones) are run simultaneously with their states synchronized. By interacting with the simpler simulator, the user can work with a simpler interface without having to deal with the complexities, since these are hidden away by the co-simulation synchronization.

On the other hand, SUMMIT does not attempt to do any co-simulation - we instead provide a bunch of features to allow users to work with SUMO maps, together with some built-in scripts to simulate interactive heterogeneous traffic. Our aim is to empower the user to work on unregulated/semi-regulated driving (in a crowd) problems.

Thus, co-simulation abstracts away various complexities so that the user can work with a simpler interface. SUMMIT assumes the user is still working in the "complex simulator" space, and empowers the user with a richer combination of features.

Hope this clarifies, let us know if you have more doubts!

**Comment by cindycia** [comment]
> you have done a so amazing project. I'm curious about a question.
> Is the projct the same as carla0.9.8/co-simulaton？
> I need to redefine my study route depending on your answer.

Hi @sheepwxy ,

We are featuring a more sophisticated motion model than the co-simulation. Traffic agents can conduct very complex behaviors. Check our [video](https://www.youtube.com/watch?v=dNiR0z2dROg&feature=youtu.be) (at around 1 minute) for a side-by-side comparison with simple motion models (Reactive TTC).

SUMMIT also comes with a more advanced [planner](https://github.com/AdaCompNUS/context-pomdp) that can be used to drive a vehicle of interest and gather high-quality expert data.

**Comment by sheepwxy** [comment]
yes，you have solved my  question.  And it does help for my further study.
@LeeYiyuan

**Comment by sheepwxy** [comment]
The complex behaviors and the advanced planner are key features. 
And they also are badly needed features by me.
Thanks for your reply.
@cindycia

**Comment by LeeYiyuan** [comment]
@sheepwxy Great! All the best for your work :) Do let us know if you have any more queries.
